// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(zkas_mobileFFI)
    import zkas_mobileFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zkas_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zkas_mobile_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

/**
 * Holds a spending key and authorizes payments with it.
 *
 * Construct it once per session from Keychain/Keystore material and let it drop
 * when done; the key is zeroized on drop.
 */
public protocol SignerProtocol: AnyObject {
    /**
     * The 64-hex key this signer actually signs with.
     *
     * A phrase is the DEVICE master and account 0 is its first wallet, which is
     * the same rule the wallet applies — so a phrase yields the same address
     * here as it does there. A 64-hex secret is already a key and is used as-is.
     */
    func accountKey() throws -> String

    /**
     * The `zkas:` address that receives funds. Public — safe to display, print
     * and share.
     */
    func address(network: String) throws -> String

    /**
     * Sign a message, proving control of this wallet's address without spending.
     * Returns `fvk ‖ sig` hex, which discloses viewing capability by design.
     */
    func signMessage(network: String, message: String) throws -> String

    /**
     * Authorize a payment the daemon prepared — the security boundary of the
     * whole protocol.
     *
     * This reconstructs the bundle, checks it pays exactly `to_address` and
     * `amount_sompi` with everything else returning as change, checks the fee is
     * within `max_fee_sompi`, recomputes the sighash from the bundle it just
     * CHECKED, and only then signs. A daemon that returns a payment to itself is
     * refused here.
     *
     * Pass the recipient and amount the USER entered, never values echoed back
     * by the daemon — that is what makes the check meaningful.
     *
     * There is deliberately no "just sign this" call in this library. A raw
     * spend-authorization signature over a bundle nobody checked is a blind
     * signature, and it is exactly what this step exists to prevent.
     */
    func verifyAndSignPayment(network: String, toAddress: String, amountSompi: UInt64, maxFeeSompi: UInt64, bundleHex: String, disclosureJson: String, alphasJson: String) throws -> String

    /**
     * The 96-byte full viewing key, hex-encoded — what a wallet service needs to
     * find this wallet's notes.
     *
     * Handing it over discloses every amount and memo this wallet ever receives,
     * forever, and cannot be revoked without moving the funds. It carries no
     * spending authority.
     */
    func viewingKey() throws -> String
}

/**
 * Holds a spending key and authorizes payments with it.
 *
 * Construct it once per session from Keychain/Keystore material and let it drop
 * when done; the key is zeroized on drop.
 */
open class Signer:
    SignerProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zkas_mobile_fn_clone_signer(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zkas_mobile_fn_free_signer(pointer, $0) }
    }

    /**
     * From a 12-word recovery phrase or a legacy 64-character hex key.
     *
     * Validated immediately by deriving an address, so a typo fails here rather
     * than at the moment someone tries to spend.
     */
    public static func fromSecret(secret: String, network: String) throws -> Signer {
        return try FfiConverterTypeSigner.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
            uniffi_zkas_mobile_fn_constructor_signer_from_secret(
                FfiConverterString.lower(secret),
                FfiConverterString.lower(network), $0
            )
        })
    }

    /**
     * The 64-hex key this signer actually signs with.
     *
     * A phrase is the DEVICE master and account 0 is its first wallet, which is
     * the same rule the wallet applies — so a phrase yields the same address
     * here as it does there. A 64-hex secret is already a key and is used as-is.
     */
    open func accountKey() throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
            uniffi_zkas_mobile_fn_method_signer_account_key(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * The `zkas:` address that receives funds. Public — safe to display, print
     * and share.
     */
    open func address(network: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
            uniffi_zkas_mobile_fn_method_signer_address(self.uniffiClonePointer(),
                                                        FfiConverterString.lower(network), $0)
        })
    }

    /**
     * Sign a message, proving control of this wallet's address without spending.
     * Returns `fvk ‖ sig` hex, which discloses viewing capability by design.
     */
    open func signMessage(network: String, message: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
            uniffi_zkas_mobile_fn_method_signer_sign_message(self.uniffiClonePointer(),
                                                             FfiConverterString.lower(network),
                                                             FfiConverterString.lower(message), $0)
        })
    }

    /**
     * Authorize a payment the daemon prepared — the security boundary of the
     * whole protocol.
     *
     * This reconstructs the bundle, checks it pays exactly `to_address` and
     * `amount_sompi` with everything else returning as change, checks the fee is
     * within `max_fee_sompi`, recomputes the sighash from the bundle it just
     * CHECKED, and only then signs. A daemon that returns a payment to itself is
     * refused here.
     *
     * Pass the recipient and amount the USER entered, never values echoed back
     * by the daemon — that is what makes the check meaningful.
     *
     * There is deliberately no "just sign this" call in this library. A raw
     * spend-authorization signature over a bundle nobody checked is a blind
     * signature, and it is exactly what this step exists to prevent.
     */
    open func verifyAndSignPayment(network: String, toAddress: String, amountSompi: UInt64, maxFeeSompi: UInt64, bundleHex: String, disclosureJson: String, alphasJson: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
            uniffi_zkas_mobile_fn_method_signer_verify_and_sign_payment(self.uniffiClonePointer(),
                                                                        FfiConverterString.lower(network),
                                                                        FfiConverterString.lower(toAddress),
                                                                        FfiConverterUInt64.lower(amountSompi),
                                                                        FfiConverterUInt64.lower(maxFeeSompi),
                                                                        FfiConverterString.lower(bundleHex),
                                                                        FfiConverterString.lower(disclosureJson),
                                                                        FfiConverterString.lower(alphasJson), $0)
        })
    }

    /**
     * The 96-byte full viewing key, hex-encoded — what a wallet service needs to
     * find this wallet's notes.
     *
     * Handing it over discloses every amount and memo this wallet ever receives,
     * forever, and cannot be revoked without moving the funds. It carries no
     * spending authority.
     */
    open func viewingKey() throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
            uniffi_zkas_mobile_fn_method_signer_viewing_key(self.uniffiClonePointer(), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSigner: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Signer

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Signer {
        return Signer(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Signer) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Signer {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Signer, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSigner_lift(_ pointer: UnsafeMutableRawPointer) throws -> Signer {
    return try FfiConverterTypeSigner.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSigner_lower(_ value: Signer) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSigner.lower(value)
}

/**
 * A newly generated wallet. Both fields are returned once and never again.
 */
public struct GeneratedWallet {
    /**
     * The 12-word BIP-39 recovery phrase. **This is the secret.** It restores
     * the wallet anywhere, forever.
     */
    public var mnemonic: String
    /**
     * The `zkas:` shielded address the phrase derives.
     */
    public var address: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The 12-word BIP-39 recovery phrase. **This is the secret.** It restores
         * the wallet anywhere, forever.
         */ mnemonic: String,
        /* 
            * The `zkas:` shielded address the phrase derives.
            */ address: String
    ) {
        self.mnemonic = mnemonic
        self.address = address
    }
}

extension GeneratedWallet: Equatable, Hashable {
    public static func == (lhs: GeneratedWallet, rhs: GeneratedWallet) -> Bool {
        if lhs.mnemonic != rhs.mnemonic {
            return false
        }
        if lhs.address != rhs.address {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(mnemonic)
        hasher.combine(address)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeneratedWallet: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeneratedWallet {
        return
            try GeneratedWallet(
                mnemonic: FfiConverterString.read(from: &buf),
                address: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: GeneratedWallet, into buf: inout [UInt8]) {
        FfiConverterString.write(value.mnemonic, into: &buf)
        FfiConverterString.write(value.address, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGeneratedWallet_lift(_ buf: RustBuffer) throws -> GeneratedWallet {
    return try FfiConverterTypeGeneratedWallet.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGeneratedWallet_lower(_ value: GeneratedWallet) -> RustBuffer {
    return FfiConverterTypeGeneratedWallet.lower(value)
}

public enum SignerError {
    /**
     * The underlying signer refused the input. Safe to show: it never contains
     * key material.
     *
     * The field is `reason`, not `message`. UniFFI turns this into a Kotlin
     * class extending Exception, which already declares `message` — naming it
     * that produces a conflicting declaration that fails the Kotlin build while
     * Swift compiles happily, so the clash only shows up on one platform.
     */
    case Signer(reason: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignerError: FfiConverterRustBuffer {
    typealias SwiftType = SignerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .Signer(
                reason: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignerError, into buf: inout [UInt8]) {
        switch value {
        case let .Signer(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
        }
    }
}

extension SignerError: Equatable, Hashable {}

extension SignerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

/**
 * The address of one account of a phrase, without handling the key.
 *
 * Accounts are `m/32'/111111'/account'`. Useful for showing a user their
 * accounts, or discovering which ones have history, without deriving keys.
 */
public func accountAddress(phrase: String, network: String, account: UInt32) throws -> String {
    return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
        uniffi_zkas_mobile_fn_func_account_address(
            FfiConverterString.lower(phrase),
            FfiConverterString.lower(network),
            FfiConverterUInt32.lower(account), $0
        )
    })
}

/**
 * Generate a new wallet: a 12-word recovery phrase and its address.
 *
 * Twelve words is not a shortcut. An Orchard key lives on the Pallas curve,
 * whose ~128-bit security caps what any seed can buy; a longer phrase would be
 * more to write down for no more strength.
 */
public func generateWallet(network: String) throws -> GeneratedWallet {
    return try FfiConverterTypeGeneratedWallet.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
        uniffi_zkas_mobile_fn_func_generate_wallet(
            FfiConverterString.lower(network), $0
        )
    })
}

/**
 * True for a valid BIP-39 phrase — checksum included, so a mistyped word is
 * caught before it becomes an empty wallet.
 */
public func isValidMnemonic(phrase: String) -> Bool {
    return try! FfiConverterBool.lift(try! rustCall {
        uniffi_zkas_mobile_fn_func_is_valid_mnemonic(
            FfiConverterString.lower(phrase), $0
        )
    })
}

/**
 * Check a signature made by `Signer::sign_message` against an address.
 * Needs no key, so it is safe to run anywhere.
 */
public func verifyMessage(address: String, message: String, signatureHex: String) throws -> Bool {
    return try FfiConverterBool.lift(rustCallWithError(FfiConverterTypeSignerError.lift) {
        uniffi_zkas_mobile_fn_func_verify_message(
            FfiConverterString.lower(address),
            FfiConverterString.lower(message),
            FfiConverterString.lower(signatureHex), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zkas_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_zkas_mobile_checksum_func_account_address() != 1057 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_func_generate_wallet() != 31304 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_func_is_valid_mnemonic() != 52094 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_func_verify_message() != 13469 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_method_signer_account_key() != 59785 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_method_signer_address() != 16517 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_method_signer_sign_message() != 52243 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_method_signer_verify_and_sign_payment() != 43587 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_method_signer_viewing_key() != 18334 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_zkas_mobile_checksum_constructor_signer_from_secret() != 64227 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
